modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory

authors="Shadows_of_Fire" #optional

license="MIT License" #mandatory

[[mods]] #mandatory

modId="placebo" #mandatory

version="8.6.3" #mandatory

displayName="Placebo" #mandatory

description='''1 (one) library boi'''

[[dependencies.placebo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"